
DATA_PATHS:
  IMAGE_DIR_PATH: ../../dataset/squares
  LABELS_JSON_PATH: ../../dataset/labels/labels.json

TRAIN:
  train_size: 0.8
  lr: 0.001
  batch_size: 4
  num_workers: -1
  momentum: 0.9
  num_epochs: 1
  print_interval: 200
  model_path: ../../saved_model/model.pkl