
to_tensor:
  _target_: torchvision.transforms.ToTensor

resize:
  _target_: torchvision.transforms.Resize
  size: [64, 64]

normalize:
  _target_: torchvision.transforms.Normalize
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]