
data_paths:
  image_dir_path: ../../dataset/squares
  train_json_path: ../../dataset/labels/train_labels.json
  val_json_path: ../../dataset/labels/val_labels.json

model_paths:
  model_path: saved_model/model.pkl